export const ADM_ENTITIES_COUNT = {
  CASCADE_MODE: Deno.env.get("FRESH_PUBLIC_CASCADE_MODE_ADM_ENTITIES_COUNT")
    ? parseInt(Deno.env.get("FRESH_PUBLIC_CASCADE_MODE_ADM_ENTITIES_COUNT")!)
    : 10,
  GLOBAL_MODE: Deno.env.get("FRESH_PUBLIC_GLOBAL_MODE_ADM_ENTITIES_COUNT")
    ? parseInt(Deno.env.get("FRESH_PUBLIC_GLOBAL_MODE_ADM_ENTITIES_COUNT")!)
    : 10,
};

export const ADM_ENTITIES_SEARCH_MIN_LENGTH =
  Deno.env.get("FRESH_PUBLIC_SEARCH_MIN_LENGTH")
    ? Number(Deno.env.get("FRESH_PUBLIC_SEARCH_MIN_LENGTH")!)
    : 3;

export const ADM_ENTITIES_SEARCH_DEBOUNCE_DELAY =
  Deno.env.get("FRESH_PUBLIC_SEARCH_DEBOUNCE_DELAY")
    ? Number(Deno.env.get("FRESH_PUBLIC_SEARCH_DEBOUNCE_DELAY")!)
    : 300;

export const UNREFERENCED_ADM_GEOJSON_CLEANUP_INTERVAL =
  Deno.env.get("FRESH_PUBLIC_UNREFERENCED_ADM_GEOJSON_CLEANUP_INTERVAL")
    ? Number(
      Deno.env.get("FRESH_PUBLIC_UNREFERENCED_ADM_GEOJSON_CLEANUP_INTERVAL")!,
    )
    : 300;
