export const GEOLOCATION_TIMEOUT =
  Deno.env.get("FRESH_PUBLIC_GEOLOCATION_TIMEOUT")
    ? parseInt(Deno.env.get("FRESH_PUBLIC_GEOLOCATION_TIMEOUT")!)
    : 10000;

export const GEOLOCATION_COORDINDATE_EPSILON =
  Deno.env.get("FRESH_PUBLIC_GEOLOCATION_COORDINDATE_EPSILON")
    ? parseFloat(Deno.env.get("FRESH_PUBLIC_GEOLOCATION_COORDINDATE_EPSILON")!)
    : 0.00001;
